#!/usr/bin/env python3
"""Simple FastAPI service to receive fall detection events from embedded devices.

Endpoints
---------
POST /event
    Accepts JSON payloads from the Arduino/ESP32 fall detection sketch. Stores the
    latest event per device in memory.
GET /latest
    Returns the most recent event for a given device_id (or all devices if omitted).
GET /health
    Basic health endpoint so dashboards/monitors can test availability.

Run with:
    /home/abhijit-suhas/esw/IOMT-eswproj/Zzz/.venv/bin/python -m uvicorn Zzz.fall_api:app --host 0.0.0.0 --port 8200
"""
from __future__ import annotations

import threading
import time
from datetime import datetime, timezone
from typing import Dict, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

app = FastAPI(title="Fall Detection API", version="1.0.0")

# Allow cross-origin requests so the Streamlit dashboard can poll locally or across devices.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
    allow_credentials=True,
)


class FallEvent(BaseModel):
    """Incoming payload from the embedded fall detector."""

    device_id: str = Field(..., description="Device identifier (e.g., esp32-mpu6050-01)")
    fall: bool = Field(True, description="Whether the device classified this window as a fall")
    svm: Optional[float] = Field(
        None,
        description="Sum Vector Magnitude (m/s^2) at the moment of detection",
    )
    ax: Optional[float] = Field(None, description="Acceleration X (m/s^2)")
    ay: Optional[float] = Field(None, description="Acceleration Y (m/s^2)")
    az: Optional[float] = Field(None, description="Acceleration Z (m/s^2)")
    gx: Optional[float] = Field(None, description="Gyroscope X (rad/s)")
    gy: Optional[float] = Field(None, description="Gyroscope Y (rad/s)")
    gz: Optional[float] = Field(None, description="Gyroscope Z (rad/s)")
    temperature_c: Optional[float] = Field(None, description="On-board temperature sensor (°C)")
    ts: Optional[float] = Field(
        None,
        description="Unix timestamp (seconds) generated by the device. Defaults to server time.",
    )


class FallEventResponse(BaseModel):
    device_id: str
    fall: bool
    svm: Optional[float]
    ax: Optional[float]
    ay: Optional[float]
    az: Optional[float]
    gx: Optional[float]
    gy: Optional[float]
    gz: Optional[float]
    temperature_c: Optional[float]
    ts: float
    iso_timestamp: str
    received_at: float
    received_iso: str
    millis_elapsed: float


_LAST_EVENTS: Dict[str, FallEventResponse] = {}
_LOCK = threading.Lock()


def _now() -> float:
    return time.time()


def _iso(ts: float) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()


def _create_fall_record(payload: FallEvent) -> FallEventResponse:
    """Create a FallEventResponse from an incoming payload."""
    event_ts = float(payload.ts) if payload.ts is not None else _now()
    received = _now()
    return FallEventResponse(
        device_id=payload.device_id,
        fall=bool(payload.fall),
        svm=payload.svm,
        ax=payload.ax,
        ay=payload.ay,
        az=payload.az,
        gx=payload.gx,
        gy=payload.gy,
        gz=payload.gz,
        temperature_c=payload.temperature_c,
        ts=event_ts,
        iso_timestamp=_iso(event_ts),
        received_at=received,
        received_iso=_iso(received),
        millis_elapsed=max(0.0, (received - event_ts) * 1000.0),
    )


@app.post("/event", response_model=FallEventResponse)
def post_event(payload: FallEvent) -> FallEventResponse:
    """Store the most recent fall event for a device."""
    record = _create_fall_record(payload)
    with _LOCK:
        _LAST_EVENTS[payload.device_id] = record
    return record


class SimpleFallAlert(BaseModel):
    """Simple fall alert payload from Arduino (matches /alert/fall endpoint)."""
    event: str = Field("fall", description="Event type")
    sensor: str = Field("MPU-6050", description="Sensor used for detection")


@app.post("/alert/fall", response_model=FallEventResponse)
def alert_fall(
    payload: SimpleFallAlert,
    device_id: str = Query("esp32-mpu6050-01", description="Device identifier"),
) -> FallEventResponse:
    """Receive simple fall alert from Arduino/ESP32.
    
    This endpoint accepts the simpler JSON format sent by the Arduino code:
    {"event": "fall", "sensor": "MPU-6050"}
    
    The device_id is passed as a query parameter.
    """
    # Convert simple alert to full FallEvent
    full_event = FallEvent(
        device_id=device_id,
        fall=True,  # Alert means fall detected
        svm=None,
        ax=None, ay=None, az=None,
        gx=None, gy=None, gz=None,
        temperature_c=None,
        ts=None,  # Will use server time
    )
    record = _create_fall_record(full_event)
    with _LOCK:
        _LAST_EVENTS[device_id] = record
    return record


@app.get("/latest")
def get_latest(device_id: Optional[str] = Query(None, description="Optional device filter")):
    """Retrieve the most recent fall event(s)."""

    with _LOCK:
        if device_id:
            record = _LAST_EVENTS.get(device_id)
            if record is None:
                raise HTTPException(status_code=404, detail="No events recorded for this device")
            return record
        return {
            "devices": {did: rec for did, rec in _LAST_EVENTS.items()},
            "count": len(_LAST_EVENTS),
        }


@app.get("/health")
def health():
    with _LOCK:
        return {
            "status": "ok",
            "devices_tracked": len(_LAST_EVENTS),
        }


@app.delete("/clear")
def clear_all():
    """Clear all fall events from memory."""
    with _LOCK:
        count = len(_LAST_EVENTS)
        _LAST_EVENTS.clear()
    return {"message": f"Cleared {count} event(s)", "count": count}


@app.delete("/clear/{device_id}")
def clear_device(device_id: str):
    """Clear fall event for a specific device."""
    with _LOCK:
        if device_id in _LAST_EVENTS:
            del _LAST_EVENTS[device_id]
            return {"message": f"Cleared event for {device_id}"}
        raise HTTPException(status_code=404, detail="No event found for this device")


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("Zzz.fall_api:app", host="0.0.0.0", port=8200, reload=False)
